# Generated by Django 2.0.4 on 2018-04-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=100)),
                ('item_price', models.FloatField()),
                ('purchase_count', models.FloatField()),
                ('merchant_address', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=100)),
            ],
        ),
    ]
